apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-waf-admission-controller
  namespace: nginx-ingress
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ingress-waf-admission-controller
  template:
    metadata:
      labels:
        app: ingress-waf-admission-controller
    spec:
      containers:
      - name: webhook
        image: ghcr.io/turbine-kreuzberg/ingress-waf-admission-controller:latest
        ports:
        - name: metrics
          containerPort: 8080
        - name: webhook
          containerPort: 9443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9443
            scheme: HTTPS
        volumeMounts:
        - name: certs
          mountPath: "/tmp/k8s-webhook-server/serving-certs/"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: ingress-waf-certificate
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-waf
  namespace: nginx-ingress
spec:
  selector:
    app: ingress-waf-admission-controller
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
    - name: webhook
      protocol: TCP
      port: 9443
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ingress-waf
  labels:
    app: ingress-waf
  annotations:
    cert-manager.io/inject-ca-from: nginx-ingress/ingress-waf-certificate
webhooks:
  - name: ingress-waf.nginx-ingress.svc.cluster.local
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["ingresses"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: ingress-waf
        namespace: nginx-ingress
        path: "/webhook"
        port: 9443
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-waf-certificate
  namespace: nginx-ingress
spec:
  secretName: ingress-waf-certificate
  dnsNames:
  - ingress-waf.nginx-ingress.svc
  issuerRef:
    name: ingress-waf-selfsign-issues
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ingress-waf-selfsign-issues
  namespace: nginx-ingress
spec:
  selfSigned: {}
